### ISSUE TITLE
Windows version always exits after [P2]  Setup took ... sec

### ISSUE THREAD

**Issue by chilio** [madMAx43v3r/mmx-binaries#1]
Hi @madMAx43v3r, thanks for making this great piece of software again.

I just wanted you to know that I've tried to run it on windows and on all k sizes and all stream sizes it crashes after [P2] setup...
Toggling DirectIO also does not change anything.
No errors, here is how it looks like:
![image](https://user-images.githubusercontent.com/5613137/213028687-514d2074-6161-47b3-b312-14d1e71d3a1d.png)
In logs it looks like this terminal problem:
![image](https://user-images.githubusercontent.com/5613137/213030205-116db5ff-2d7b-43d7-9fc9-d69636e5eaf0.png)

My setup:
Win 10 22H2 19045.2486
AMD Ryzen 9 3900X
128 GB DDR4 3200
RTX 3080 Ti 12 GB
Can you suggest what to troubleshoot further?

**Comment by madMAx43v3r** [comment]
I forgot to test partial RAM mode, it doesnt work yet sorry..

**Comment by madMAx43v3r** [comment]
fixed

**Comment by chilio** [comment]
I can confirm it works as expected. Great job @madMAx43v3r
