### ISSUE TITLE
NativeCommandError while plotting with cuda_plot_k32 on Windows.

### ISSUE THREAD

**Issue by chilio** [madMAx43v3r/mmx-binaries#10]
I've came across this error randomly.
![image](https://user-images.githubusercontent.com/5613137/214705769-cfb4b489-36c7-4b89-83fa-65211c3f37ce.png)
However plotting process is not exited and finally completed.
So why this might happen? Are plots generated with this error valid?
System:
Windows 10
Tmp dirs on NVME.
Destination dir on another NVME.

**Comment by madMAx43v3r** [comment]
yeah it can happen sometimes, the plot is fine.
