### ISSUE TITLE
[Solved] plot-sink reading target drives from a file - enabling "hot swap"

### ISSUE THREAD

**Issue by Jacek-ghub** [madMAx43v3r/mmx-binaries#18]
Would it be possible to have plot-sink read target drives from the file before selecting the next drive to write to?  This would let us to modify that file on the fly and remove full drives and add new ones to the target set.

Also, if possible, when the new drives would be added before the first batch is full, maybe the plot-sink could start using all drives (both from the old set and the new one), so this way the old set would be topped off, and the transition to the new set would be smoother.  This could potentially help to overcome drives slowdown when close to being full.

**Comment by madMAx43v3r** [comment]
you can restart plot sink at any time with new / more drives, no plots will be lost. you just have to wait for the current copies to finish.

**Comment by madMAx43v3r** [comment]
actually you can start a new plot sink right away in another terminal, after ctrl+c the first one. it will close the server socket right away and allow a new instance to use the port.

**Comment by Jacek-ghub** [comment]
But when the plotter is running, there are always 3 plots being copied, so there is no way to kill the plot-sink when there is no transfer.

Or you are saying that let the plotter run with -1, fill the first set of drives, choke on no free space (while buffering to NVMe) and then do the plot-sink swap/restart?

**Comment by madMAx43v3r** [comment]
even better, why not start plot sink with all your drives right away, even the full ones with old plots? it will automatically start filling drives when you make free space on them.

**Comment by Jacek-ghub** [comment]
Oh, I didn't realize that!  This may be a very good info to add to github Readme.

I assumed that once ctrl+c was ussed, the sink just aborted on the current plot, so those got orphaned.

I am doing sneakernet for those drives, so no problem to start with all, but at some point there is a need to unmount the full ones and bring the empty ones to the box.  During this time the folder that is using to mount those drives is being exposed, so I thought that plot-sink will not like that.  

Would be really nice, if such folders could be marked as "do-not-use.txt" or so, so plot-sink would skip those when drives are unmounted.

**Comment by madMAx43v3r** [comment]
I just made a fix to the plot sink (not compiled for windows yet), so it don't get stuck when all drives are full and no more copies are incoming.

>  During this time the folder that is used to mount those drives is being exposed, so I thought that plot-sink will not like that.

yeah that's an issue... it would fill your system drive.

> Would be really nice, if such folders could be marked as "do-not-use.txt"

that's a good idea yes.

**Comment by madMAx43v3r** [comment]
> Oh, I didn't realize that! This may be a very good info to add to github Readme.

It's in the GPU plotter readme: 
https://github.com/madMAx43v3r/mmx-binaries/tree/master/mmx-cuda-plotter#remote-copy

**Comment by Jacek-ghub** [comment]
Yay!!! You are THE MAN!

Thank you so much for looking into this issue.  I am sure more people will appreciate those changes.

**Comment by Jacek-ghub** [comment]
> It's in the GPU plotter readme:

As always, I read that readme, but glanced over that.  Sorry for that.

**Comment by madMAx43v3r** [comment]
Ok implemented the disable feature, a file called `chia_plot_sink_disable` or `chia_plot_sink_disable.txt` (for you windows guys, I know how hard it is to create a file without extension lol) will disable a folder from being used.

However I have not updated the Windows binary yet, need to reboot...

**Comment by madMAx43v3r** [comment]
plot sink is open source actually, you can compile it via `make_msvc.bat` on windows: https://github.com/madMAx43v3r/chia-plot-sink
(need to have [Visual Studio](https://visualstudio.microsoft.com/vs/features/cplusplus/) installed)

**Comment by Jacek-ghub** [comment]
Hey, I am plotting on Linux (Dell t7610) and have no preference, lol.  

I guess, for those on Win, having such extension makes it easier to use file explorer to create such file (there is a "raw text file" option), or select it there to open (for some people an empty file may be a new concept) without explorer asking what app to use, ...

**Comment by Jacek-ghub** [comment]
I really love how the plot-sink-disable feature works!  

I had some hiccups with plot-sink crashing today and got it going by adding two extra drives and playing with that plot-write block.  Super easy, and super useful (at least for me).

One thing that potentially could be considered and may throw off some people is that those to-be-mounted folders need to have the same folder structure as the drives will have when mounted.  At least, for me that was not a problem, as I have it the same way on every drive (/mmx/plots), but I saw that some people name those subfolders as well.  So, the first try crashed on me, as the structure was not there, but once I added it, it was really smoot sailing.

Thank you again for implementing it.  Real time saver for me.

**Comment by madMAx43v3r** [comment]
Can you describe in more detail what made it crash?

**Comment by Jacek-ghub** [comment]
I am afraid that I cannot.  

Last night, there was another crash.  In both cases, the shell that was running plot-sink was gone.  I didn't tee the output to a file, so really have no user level output.  I will start it soon, and this time i will tee it.  If you know what should I look in the logs, I will chase it.  This is a fresh install of Ubuntu 22:10. Not much installed, except the binaries, basically byptop, nvtop, screen, psensor, cockpit and xrdp (maybe something else along those lines).  The box is used only for plotting (don't user browser, etc. on it, just shell, file manager, text editor, psensor and resource monitor).  I run xRDP to the box, and keep it open in a separate virtual desktop.   I also ssh to the box to get bpytop out of the way.

The second crash happened, when I was about to shut down the server to see whether target drives can somehow get better speeds.  The steps I took before the second crash:
1. ctrl+c on the plotter
2. 4 plots on NVMe
3. 4 parallel writes in plot-sink
4. plotter finished, and was waiting for plot-sink to finish
5. plot-sink finished 2 writes
6. plot-sink crashed, shell window was terminated

The total disk write speed (across 5 drives) was around 300 MBps.  plot-sink reported plots were in the range of 80-120 MBps, mostly running 4 writes in parallel.  That would imply that the actual total write was closer to 400 MBps

NVMe was reporting read activities from 100-800 MBps jumping all over the board, but not going much over 800 MBps.  It is Samsung 970 EVO plus 1 TB.  It has a 60 mm fan blowing over it, so it runs at around 35 C.

Box has 256 GB RAM and Xeon e5-2695 v2 CPU with a watercooler (runs around 40 C while running cuda plotter.  I added 120mm fan over RAM, so it runs around 50 C.

Nothing really stands out.  I used this box for CPU plotting, and never had a single crash, although most was done under Rocky Linux 9.1 (RHEL).  I have tried to install Fedora, but couldn't get nvidia to cooperate, so switched to Ubuntu for GPU plotting.

The GPU is brand new 3060 Ti / 8GB GDDR6 LHR (Zotac).

The only things on the box that can influence potential write speed across those 5 drives are either NVMe (have a second one in CPU2 slot, will switch to it after running some test on NVMe) or SAS/SATA controller.  SAS/SATA controller is LSI with 2x 4 ports standard SFF connector.  All drives are hanging on that LSI chip.  There is one more straight SATA connector that holds OS drive.

If you have any pointers what I can do to chase it, I will give it a run.  If you want to generate an instrumented build, I can run that as well.  Although, those crashes are not happening right away, so it may take a day or so to catch one (in both cases, plotter/sink were running over 12 hours or so).

**Comment by madMAx43v3r** [comment]
> shell window was terminated

That's really strange, normally this cannot be caused by the program being run...

**Comment by madMAx43v3r** [comment]
Indeed there was a bug that could cause a crash on shutdown, should be fixed now. Windows binaries not yet updated though...

**Comment by Jacek-ghub** [comment]
The first crash happened, when the plotter was still working, there was no shutdown.  When I checked on the box, the plotter was stuck on both NVMe being full, and plot-sink missing.  Once I restarted plot-sink, plotter happily continued to work.

**Comment by madMAx43v3r** [comment]
I mean on shutdown of plot sink
