### ISSUE TITLE
mmx-cuda-plotter doesn't back off when new plot is finished, but rather starts a second plot xfr per HD

### ISSUE THREAD

**Issue by Jacek-ghub** [madMAx43v3r/mmx-binaries#31]
I started mmx-cuda-plotter with 4 target drives:

`mm/cuda_plot_k32_f24  -n -1 -x 11337 -C 7 -t /mnt/nvme/mmx/tmp1/ -d /mnt/d1/mmx/plots/ -d /mnt/d2/mmx/plots/ -d /mnt/d3/mmx/plots/ -d /mnt/d4/mmx/plots/ -f fff -p ppp
`

Looks like that at some point, writes to destination HDs slowed down, and when a new plot was finished, instead of letting it sit on the NVMe, the plotter started another write to the drive that was already being written to.  This is basically killing such drive write performance, as such, those writes start to snowball right now.

Would it be possible to have the new plot sit on NVMe (yes, eventually choking NVMe), as that could potentially help those drives to recover.

Here is what I see right now:

```
-rw-rw-r-- 1 bull bull  56G Feb  5 14:33 /mnt/d1/mmx/plots/plot-mmx-k32-c7-2023-02-05-14-15-e9c8f895c2cb3a17d45d9c81f8ff74337906e0a2517d1c2ac07179a6dbbec090.plot.tmp
-rw-rw-r-- 1 bull bull 8.8G Feb  5 14:33 /mnt/d1/mmx/plots/plot-mmx-k32-c7-2023-02-05-14-27-8323f3b96a9cc09b172e7dcdd50780ff78cb2a8c978a6b8dad2f1e60d5814fa1.plot.tmp
-rw-rw-r-- 1 bull bull  47G Feb  5 14:33 /mnt/d2/mmx/plots/plot-mmx-k32-c7-2023-02-05-14-18-06db62c80f193dbe9e5f9a9c8acc7e8d7d69276c77f43e1e7148a20d4f5e6c14.plot.tmp
-rw-rw-r-- 1 bull bull  75G Feb  5 14:33 /mnt/d3/mmx/plots/plot-mmx-k32-c7-2023-02-05-14-09-a56b5de62045ce8981badc876cab9d9d21b966f6cc806e3d790a844b4bcff8a3.plot.tmp
-rw-rw-r-- 1 bull bull  30G Feb  5 14:33 /mnt/d3/mmx/plots/plot-mmx-k32-c7-2023-02-05-14-21-194df4e3a53e12dc4dde1df68daf8df32ce971025dda3b959c07e252570be269.plot.tmp
-rw-rw-r-- 1 bull bull  41G Feb  5 14:33 /mnt/d4/mmx/plots/plot-mmx-k32-c7-2023-02-05-14-24-6646093fd7a0e5255e2ebc90f22db8b1fe9ce3276cabff8ff6e17cedd5fd9078.plot.tmp
```
There are 2 writes on d1 and d3.

Actually, plot-sink has right now a nice feature that permits to add "overflow" HDs that could be connected if needed.  It would be really nice if that feature would be also available in cuda-plotter.

**Comment by madMAx43v3r** [comment]
Hmm yeah the current implementation of `-d` is not very smart, I wanted to avoid duplicating all the code that's in plot sink already...

You can use the new parameter `-Q` in the upcoming release to limit the max number of copies however.

**Comment by Jacek-ghub** [comment]
I don't think that this new param will solve the problem, rather it will kick it a bit further.  Let's assume that we start with 5 drives, where between 3-4 drives are needed to have HD writes be faster than the plotter.  Once we fill one drive (but still have room on the other 4 drives) the same problem will kick in.  The minute that will be triggered on one of those 4 drives that have room for plots, the affected drive is basically out of commission, triggering the next drive to get duplicate writes, ...

What I see on my box (Dell t7610 one e5-2695 v2) is that the total writes across all drives fluctuates a bit.  Sometimes looks like it is close to have just 2 drives, but sometimes 4 drives are struggling.  From what I see, having extra drives for whatever reason is not helping, as it really looks like a limit for the combined speed.

Also, I got a couple of e5-2630L v2 CPUs (6 phys / 12 logical).  Those are 60 W TDP CPUs.  I started with one, but it was getting saturated from time to time, and transfer speeds were suffering, so I switched back to 2695.  I am not sure why I see that slowdown but would like to blame it on Ubuntu 22.10.  Although, it may be H/W related.

**Comment by madMAx43v3r** [comment]
How are the HDDs connected? And why not use plot sink on localhost?

**Comment by Jacek-ghub** [comment]
That mobo has LSI SAS/SATA 8 ports.  So, all drives are SATA connected to that controller.

Actually, I started with the plot-sink on local host.  However, the CPU load on that 2695 was high, plus those initial problems with swapping drives (what you fixed already).  So, I have tried to use just plotter, to see if the plot-sink is introducing some extra CPU load (also got those low power CPUs at that time).  I plotted a batch with straight plotter and got into those problems with double writes.  Once that happened, I am back to plotter + sink and all is good.  So, this ticket is just my observation of what happened when I tried to use just the plotter.

I am with you to keep the plotter clean and move all the final distribution logic to plot-sink.  Another reason to do that is that the plot-sink is open source, so potentially people can chime in with enhancements to it or use it as a framework for a GUI plot manager (for those that cannot stand CLI).

The only wish for plot sink that I have right now is to add that extra RAM buffering to potentially speed up xfrs and reduce the load on NVMe.  Other than that, the hot swap of those drives, ability to quickly add overflow drives is superb.

**Comment by madMAx43v3r** [comment]
I guess you're hitting the limit of the SATA controller? 600 MB/s ?

**Comment by Jacek-ghub** [comment]
Not really.  When all goes well, I see max of 3 drives being active with average speeds around 150 MBps.  When it starts slowing down, there are 4 or so active drives around 100 MBps max sometimes dropping down to ~80MBps (more like 250MBps total).  At this point adding 5th drive doesn't usually help, as the overall write speeds is the same, but per drive speeds go down.

However, I will check whether I have an extra PCIe SATA card and will split those drives across 2 controllers.  

I can close this ticket, if you want me to do it.

**Comment by Jacek-ghub** [comment]
Also, when I run the plotter with both -t and -d pointing to NVMe, my k32 C7 plot times were around 140 secs (8 plots in a row).  On the other hand, when those plots are transferred by plot-sink, plotting speed decreases to 180-190 secs.  With that low power CPU, plot times were in 220+ secs or so range.

**Comment by madMAx43v3r** [comment]
I think your low power CPU doesnt support the higher MHz RAM speeds

**Comment by Jacek-ghub** [comment]
Yes, beside core count, they differ in bus speeds - 7.2 GT/s vs 8 GT/s, max RAM 1,600 vs 1,866 MHz thus memory bandwidth of 51.2 GB/s vs 59.7 GB/s.  Those values basically agree with the increased plotting times.

On 2695, I have about 40-50% CPU load and on 2630L it was around 70-80%, but some cores were pushing 100% rather often.  

The power saving with that low power chip was around 50 W overall, what boils down to a whopping $10 or so difference to replot 500TB farm.  :)  (Although, one such chip costs also $10.)

So, clearly not worth pursuing for plotting purposes, but may be an option for a harvester that runs 24/7.

**Comment by madMAx43v3r** [comment]
I've implement smart handling of multiple `-d` now, will be part of the upcoming release.

**Comment by Jacek-ghub** [comment]
Great!  Knowing how it was manifesting, it will be easy to test it (provide 2 target HDs and the third plot will be telling).  I will close this ticket once the binaries are released.

However, please, please, pretty please, consider implementing chunked plots / extra RAM used as primary storage that is described in https://github.com/madMAx43v3r/mmx-binaries/issues/22.  Even without plot chunking, for those that have 512 GB RAM that enhancement may hugely reduce NVMe usage (using 3 RAM plot slots) and at the same time potentially speeding up final xfrs.

**Comment by madMAx43v3r** [comment]
Now available here: https://github.com/madMAx43v3r/chia-gigahorse

**Comment by Jacek-ghub** [comment]
Thank you.  I have just downloaded new plotter and plot-sink.  Looking at the readme there, is NFT plotting supported for MMX?

**Comment by madMAx43v3r** [comment]
just for Chia, NFT for testnet doesn't make sense anyways

**Comment by Jacek-ghub** [comment]
Fixed in the latest release.
