### ISSUE TITLE
Add "stage" destination to cuda-plotter

### ISSUE THREAD

**Issue by Jacek-ghub** [madMAx43v3r/mmx-binaries#32]
Would it be possible to add stage destination to cuda-plotter?  Yes, it would increase the write load on NVMes, but would potentially quickly offload the stage drive from finished plots making writes to destination drives a little faster.

My box is Dell t7610 with one e5-2695 v2 chip (removed the second to lower the power consumption) and Samsung 970 EVO Plus.  When I run the plotter where both -t and -d are on the same NVMe, I am getting plot times just a bit over 140 secs.  On the other hand, when -d are for example 4 drives (10 TB WD Red Pro), those plots are taking a bit over 180 secs.  Potentially using a "stage" folder would decrease that 40 secs a bit.

**Comment by madMAx43v3r** [comment]
I dont follow how adding another step inbetween would change the load on `-t` ? Pretty sure it's additional load of reading the plots back from the `-t` which is slowing things down.

**Comment by Jacek-ghub** [comment]
My thinking was that with the current setup we have plotter writing to that drive, and several reads running in parallel to do the final xfr.  It looks to me that those writes take precedence over those reads, thus potentially slowing them down.  Thus having the stage at the end would let the plotter hammer on the tmp drive, and once done doing a straight xfr of that plot to stage.

It only makes sense, if there is more writes on tmp folder than the finished plot (i.e., not just dumping the plot there, but rather still doing recombination)

**Comment by madMAx43v3r** [comment]
> It only makes sense, if there is more writes on tmp folder than the finished plot (i.e., not just dumping the plot there, but rather still doing recombination)

That's all the `-t` ever does, receive the final plot files.

**Comment by Jacek-ghub** [comment]
Great, closing it as this was an uninformed request.
