### ISSUE TITLE
Expected lookup times with compressed plots

### ISSUE THREAD

**Issue by Jacek-ghub** [madMAx43v3r/mmx-binaries#33]
I have added 4x 10TB drives with k32 C7 compressed plots to my node.  As expected, the lookup times are longer, but not as stable as for non-compressed plots.  What should we be roughly expecting to see for those lookups, and at which point we should consider those lookup times as taking too long (i.e., either upgrade the GPU or use lower compression).

Here is the most recent chart with lookup times.  I added those 4 drives past midnight, and the chart changes sharply around that time.
![image](https://user-images.githubusercontent.com/85920330/217058130-cff8e287-1ba0-4292-89a0-09ab84587244.png)

The bottom band (roughly below 0.5 sec) are lookups for those non-compressed plots.  I am not sure why there are 2 bands (around 1 sec and 1.6 sec) there.  Also, not sure why are those random lookups there going up to 10 secs a couple of times.  That harvester has ~400 TB worth of plots, so those 4 drives are rather a small fraction (thus less likely those variations are due to multiple eligible compressed plots).  The chart potentially doesn't properly reflects the lookup distribution, as lookups in those banded areas are overlapping, thus hiding the density.  If needed, I can also get percentage distribution per time slices.

Although, the good part is that no other stats got affected (same distribution for eligible plots, and VDF processing looks like rock solid with no changes whatsoever after adding those compressed plots.

Here for comparison is the lookup chart for only non-compressed plots:
![image](https://user-images.githubusercontent.com/85920330/217059738-a5e18644-d899-4469-a744-fc1cd718bea1.png)

Actually, one more question about VDF times.  The node is running on k2200 for now (waiting for remote decompression to be able to use remote node / farmer to decompress plots as I am out of PCIe slots).  Beside the fact that this card is not going to cut in the long run, do we understand why the card is kind of shifting VDF processing times from time to time.  I didn't find any correlation between what else is happening on that node.  It just switches at random.  It looks as a significant shift on the chart, but is actually not, as the Y axis is just partial, thus emphasizing those small differences.  It is just curiosity, not something that has much relevance.
![image](https://user-images.githubusercontent.com/85920330/217060834-115759d3-3ad0-4f55-a0bd-fae386369291.png)

**Comment by madMAx43v3r** [comment]
The variation you observe is expected, however the more plots you have the more smooth it will become.

![image](https://user-images.githubusercontent.com/951738/217110954-b93e240f-2074-4c93-9ed1-ce7ca76b30d3.png)
Timelord speed is not constant, so VDF times are also not constant ;)

**Comment by madMAx43v3r** [comment]
On MMX anything below 50 sec lookup delay is fine.

**Comment by Jacek-ghub** [comment]
Oh, great!  When I saw those times above 5 secs, I started to panic.  Old chia's habits. :)

We spoke before about submitting "old" challenges on plot-reloading, and that is where you mentioned that 50 sec, but I still got trapped on this one.

So, it looks like we can push that k2200 a bit.
