### ISSUE TITLE
Plots created with compression are not recognized in mmx-node

### ISSUE THREAD

**Issue by chilio** [madMAx43v3r/mmx-binaries#7]
Hi @madMAx43v3r,
am I doing something wrong or is mmx-node not ready to utilize mmx plots with compression generated with cuda plotter?
`Failed to load plot 'G:plot-mmx-k32-c8-2023-01-24-15-51-3bf9f629f184706d2bf70b32f948029f4a4027057face2b06e65508fbacae7d2.plot' due to: Invalid plot file format`
Plot generation was completed successfully on Windows.
BTW. Latest (v0.9.6) MMX-NODE used.

**Comment by madMAx43v3r** [comment]
Need the closed source version here: https://github.com/madMAx43v3r/mmx-binaries/releases
